// Code generated by mockery v1.0.0. DO NOT EDIT.

package utils

import mock "github.com/stretchr/testify/mock"

// MockDagReader is an autogenerated mock type for the DagReader type
type MockDagReader struct {
	mock.Mock
}

// ReadDag provides a mock function with given fields: path
func (_m *MockDagReader) ReadDag(path string) ([]byte, error) {
	ret := _m.Called(path)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadPathsFromDir provides a mock function with given fields: dir
func (_m *MockDagReader) ReadPathsFromDir(dir string) ([]string, error) {
	ret := _m.Called(dir)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(dir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(dir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
