package entity

import (
	mock "github.com/stretchr/testify/mock"
)

var _ BaseInfoGetter = &MockBaseInfoGetter{}

// MockBaseInfoGetter is an autogenerated mock type for the BaseInfoGetter type
type MockBaseInfoGetter struct {
	mock.Mock
}

// GetBaseInfo provides a mock function with given fields:
func (_m *MockBaseInfoGetter) GetBaseInfo() *BaseInfo {
	ret := _m.Called()

	var r0 *BaseInfo
	if rf, ok := ret.Get(0).(func() *BaseInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*BaseInfo)
		}
	}

	return r0
}
